
import React, { useState, useCallback } from 'react';
import { GoogleGenAI } from "@google/genai";
import { Controls } from './components/Controls';
import { Visualization } from './components/Visualization';
import { Player } from './components/Player';
import { Note, QuantumState, Scale, GenerationResult } from './types';
import { DEFAULT_SETTINGS, SCALES, INSTRUMENTS } from './constants';
import { Header } from './components/Header';
import { LoadingSpinner } from './components/icons/LoadingSpinner';

const App: React.FC = () => {
    const [settings, setSettings] = useState(DEFAULT_SETTINGS);
    const [generationResult, setGenerationResult] = useState<GenerationResult | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleGenerateMusic = useCallback(async () => {
        setIsLoading(true);
        setError(null);
        setGenerationResult(null);

        try {
            const { qubits, melodyLength, scale, instruments, vibe } = settings;
            const scaleName = Object.keys(SCALES).find(key => SCALES[key as keyof typeof SCALES] === scale) || 'Unknown Scale';
            const instrumentNames = instruments.map(instVal => INSTRUMENTS.find(i => i.value === instVal)?.label || instVal).join(", ");

            // 1. Quantum Simulation (Client-side)
            const numStates = 2 ** qubits;
            const quantumStates: QuantumState[] = Array.from({ length: numStates }, (_, i) => ({
                state: i.toString(2).padStart(qubits, '0'),
                probability: 1 / numStates,
            }));

            // 2. Music Mapping (Client-side)
            const melody: Note[] = [];
            const durations = ['q', 'h', '8n'];
            for (let i = 0; i < melodyLength; i++) {
                const randomOutcome = Math.floor(Math.random() * numStates);
                
                const noteIndex = randomOutcome % scale.length;
                const note = scale[noteIndex];
                const duration = durations[Math.floor(Math.random() * durations.length)] as 'q' | 'h' | '8n';
                const velocity = Math.floor(Math.random() * 48) + 80; 

                melody.push({ note, duration, velocity });
            }

            // 3. Description Generation (Gemini AI)
            let description = "";
            try {
                if (!process.env.API_KEY) {
                     throw new Error("API Key not found");
                }
                
                const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
                const melodyString = melody.map(m => m.note).join(', ');
                
                const prompt = `
                    I have generated a melody using a ${qubits}-qubit quantum simulation mapped to the ${scaleName} scale.
                    The notes are: ${melodyString}.
                    The selected mix of instruments includes: ${instrumentNames}.
                    The atmospheric vibe of this dimension is: "${vibe}".
                    
                    Please write a short, poetic, and sci-fi inspired description (max 50 words) describing the "quantum universe" or "dimension" where this specific melody originated. 
                    Acknowledge the sound texture created by combining these specific instruments (e.g. if it's chaotic, say so; if it's harmonious, say so). 
                    Incorporate the feeling of the "${vibe}". Be creative and abstract.
                `;

                const response = await ai.models.generateContent({
                    model: 'gemini-2.5-flash',
                    contents: prompt,
                    config: {
                        systemInstruction: "You are a Quantum Historian documenting the sounds of parallel realities.",
                    }
                });

                description = response.text.trim();
            } catch (aiError) {
                console.warn("AI generation failed, falling back to static text:", aiError);
                 description = `This melody was generated by locally simulating a ${qubits}-qubit quantum register in a "${vibe}" atmosphere. The soundscape is a superposition of: ${instrumentNames}.`;
            }
            
            setGenerationResult({
                quantumStates,
                melody,
                description,
            });

        } catch (e) {
            console.error(e);
            setError("Failed to generate music. An unexpected error occurred.");
        } finally {
            setIsLoading(false);
        }
    }, [settings]);

    return (
        <div className="min-h-screen bg-quantum-dark flex flex-col items-center p-4 sm:p-6 lg:p-8 font-sans">
            <Header />
            <main className="w-full max-w-7xl mx-auto mt-8 grid grid-cols-1 lg:grid-cols-12 gap-8">
                <div className="lg:col-span-4 bg-quantum-dark-2 rounded-xl p-6 shadow-lg border border-white/10">
                    <Controls settings={settings} setSettings={setSettings} onGenerate={handleGenerateMusic} isLoading={isLoading} />
                </div>

                <div className="lg:col-span-8 flex flex-col gap-8">
                     {isLoading && (
                        <div className="flex flex-col items-center justify-center h-full bg-quantum-dark-2 rounded-xl p-6 shadow-lg border border-white/10 min-h-[400px]">
                            <LoadingSpinner />
                            <p className="text-quantum-light mt-4 text-center">Simulating quantum circuit... Entangling qubits... <br/><span className="text-xs text-gray-400">Consulting the Gemini Oracle...</span></p>
                        </div>
                    )}
                    {error && (
                        <div className="flex items-center justify-center h-full bg-red-900/50 rounded-xl p-6 shadow-lg border border-red-500">
                             <p className="text-white text-center">{error}</p>
                        </div>
                    )}
                    {!isLoading && !error && generationResult && (
                      <>
                        <div className="bg-quantum-dark-2 rounded-xl p-6 shadow-lg border border-white/10">
                          <h2 className="text-xl font-bold text-quantum-light mb-4">Quantum Interpretation</h2>
                          <p className="text-gray-300 font-light italic border-l-4 border-quantum-accent pl-4">"{generationResult.description}"</p>
                        </div>
                        <Visualization quantumStates={generationResult.quantumStates} melody={generationResult.melody} />
                        <Player melody={generationResult.melody} tempo={settings.tempo} instruments={settings.instruments} />
                      </>
                    )}
                    {!isLoading && !error && !generationResult && (
                        <div className="flex flex-col items-center justify-center text-center h-full bg-quantum-dark-2 rounded-xl p-6 shadow-lg border border-white/10 min-h-[400px]">
                            <h2 className="text-2xl font-bold text-quantum-light">Welcome to the Quantum Music Generator</h2>
                            <p className="text-gray-300 mt-2 max-w-md">Select multiple instruments to create a masterpiece (or chaos), adjust parameters, and generate a unique composition.</p>
                        </div>
                    )}
                </div>
            </main>
        </div>
    );
};

export default App;
